# Use the official Ubuntu 22.04 base image
FROM ubuntu:22.04
# FROM ubuntu:xenial

# Set the timezone to Asia/Tokyo
RUN apt-get update
# RUN apt-get install -y tzdata
# RUN ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
RUN apt-get -qqy install software-properties-common git make m4 aspcud ocaml opam \
#
